# Generated by Django 2.1.1 on 2018-09-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('quantidade', models.PositiveSmallIntegerField()),
                ('verificacao', models.BooleanField(default=False)),
            ],
        ),
    ]
